# Generated by Django 3.1.4 on 2020-12-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training',
            field=models.ManyToManyField(to='app.SingleSeries'),
        ),
    ]
