# Generated by Django 3.1.4 on 2021-01-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201231_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleseries',
            name='exercise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.exercise'),
        ),
        migrations.AddField(
            model_name='singleseries',
            name='ownexercise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ownexercise'),
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
