# Generated by Django 3.1.4 on 2021-01-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210101_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
