# Generated by Django 3.1.4 on 2021-02-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210106_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleseries',
            name='AssumedReps',
            field=models.IntegerField(default=0),
        ),
    ]
