# Generated by Django 3.1.4 on 2021-02-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_singleseries_assumedreps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleseries',
            old_name='AssumedReps',
            new_name='assumedReps',
        ),
    ]
