# Generated by Django 3.1.4 on 2021-02-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210215_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleseries',
            name='assumedReps',
        ),
        migrations.AddField(
            model_name='singleseries',
            name='assumedReps',
            field=models.ManyToManyField(related_name='assumedreps', to='app.Reps'),
        ),
        migrations.AlterField(
            model_name='singleseries',
            name='reps',
            field=models.ManyToManyField(related_name='xd', to='app.Reps'),
        ),
    ]
