# Generated by Django 3.1.4 on 2021-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210215_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleseries',
            name='assumedReps',
        ),
        migrations.AlterField(
            model_name='singleseries',
            name='reps',
            field=models.ManyToManyField(to='app.Reps'),
        ),
    ]
