# Generated by Django 3.1.4 on 2021-02-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210215_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleseries',
            name='exercise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.exercise'),
        ),
        migrations.AlterField(
            model_name='singleseries',
            name='ownexercise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ownexercise'),
        ),
    ]
