# Generated by Django 3.1.4 on 2021-02-19 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210215_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleseries',
            name='reps',
        ),
        migrations.AddField(
            model_name='singleseries',
            name='reps',
            field=models.CharField(default=None, max_length=255, validators=[django.core.validators.int_list_validator]),
        ),
    ]
