# Generated by Django 3.1.4 on 2021-02-19 21:09

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210219_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleseries',
            name='reps',
            field=models.CharField(default=None, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
