export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const POST_LOGIN = 'POST_LOGIN';
export const POST_REGISTER = 'POST_REGISTER';
export const GET_MEASUREMENTS = 'GET_MEASUREMENTS';
export const POST_TRAINING = 'POST_TRAINING';
export const GET_TRAININGS = 'GET_TRAININGS';
export const GET_TRAININGS_FAILURE = 'GET_TRAININGS_FAILURE';
export const GET_TRAININGS_SUCCESS = 'GET_TRAININGS_SUCCESS';
export const GET_GOALS = 'GET_GOALS';
export const GET_GOALS_SUCCESS = 'GET_GOALS_SUCCESS';
export const GET_MEASUREMENTS_SUCCESS = 'GET_MEASUREMENTS__SUCCESS';
export const POST_MEASUREMENT = 'POST_MEASUREMENT';
export const POST_MEASUREMENT_SUCCESS = 'POST_MEASUREMENT_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

