export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_REGISTER = 'POST_REGISTER';
export const POST_LOGOUT = 'POST_LOGOUT';
export const POST_LOGOUT_AUTH = 'POST_LOGOUT_AUTH';
export const GET_MEASUREMENTS = 'GET_MEASUREMENTS';
export const POST_TRAINING = 'POST_TRAINING';
export const GET_TRAININGS = 'GET_TRAININGS';
export const GET_TRAININGS_FAILURE = 'GET_TRAININGS_FAILURE';
export const GET_TRAININGS_SUCCESS = 'GET_TRAININGS_SUCCESS';
export const GET_GOALS = 'GET_GOALS';
export const GET_GOALS_SUCCESS = 'GET_GOALS_SUCCESS';
export const GET_MEASUREMENTS_SUCCESS = 'GET_MEASUREMENTS__SUCCESS';
export const POST_MEASUREMENT = 'POST_MEASUREMENT';
export const POST_MEASUREMENT_SUCCESS = 'POST_MEASUREMENT_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";


